name: llama.cpp

defaults:
  run:
    shell: bash -el {0}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/llamacpp.yaml'
      - 'requirements/**'

  push:
    paths:
        - '.github/workflows/llamacpp.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cann: ['python3.10-cann8.0.rc2.beta1']
        build: ['Release']

    container:
      image: ascendai/cann:openeuler-${{ matrix.cann }}

    steps:
    - uses: actions/checkout@v4

    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          uname -a
          yum update -y
          yum install git cmake gcc gcc-c++ make -y  
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          mkdir build
          cd build
          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/x86_64/:${LD_LIBRARY_PATH}
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DGGML_CANN=on -DSOC_TYPE=ascend910b3 && cmake --build .
          
  ubuntu-unit-tests:

    runs-on: ubuntu-latest

    container:
      image: ascendai/cann

    steps:
    - uses: actions/checkout@v4
        
    - name: Install llamacpp
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 30
        max_attempts: 3
        retry_on: error
        command: |
          uname -a
          apt-get update -y
          apt-get install git cmake build-essential make -y   
          git clone https://github.com/ggerganov/llama.cpp.git

    - name: Build
      run: |
          cd llama.cpp
          export LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib/:${LD_LIBRARY_PATH}
          cmake -B build -DCMAKE_BUILD_TYPE=release -DGGML_CANN=on -DSOC_TYPE=ascend910b3 && cmake --build build -j $(nproc)
          
  ubuntu-arm64-test:
      runs-on: ubuntu-latest
      
      steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Run ARM64 Docker image
        run: |
          docker pull arm64v8/ubuntu:latest
          docker run --rm arm64v8/ubuntu:latest uname -m
    
    
    
